import Link from "next/link";
import { ArrowRight, Bot, Compass, LayoutGrid, Newspaper, PanelsTopLeft, Sparkles, Wrench } from "lucide-react";
import { AppShell } from "@/components/app-shell";

const areas = [
  { title: "Explore tools", text: "Practical converters, calculators, formatters, and generators for everyday technical work.", href: "/explore", icon: Wrench },
  { title: "AI Apps", text: "Focused AI workspaces for writing, code, imagery, and conversation—built around useful outcomes.", href: "/ai-apps", icon: Bot },
  { title: "Widgets", text: "Independent, ready-to-use information and utility widgets for the work you do every day.", href: "/widgets", icon: LayoutGrid },
  { title: "Portals", text: "Specialized destinations for learning, career growth, technology, language, and more.", href: "/portals", icon: PanelsTopLeft },
];
const highlights = [
  { label: "Tools", title: "Move from question to answer", text: "Discover useful utilities without losing your place in the broader platform.", icon: Compass },
  { label: "AI Apps", title: "Purpose-built creative workspaces", text: "Start with a clear task, use a focused interface, and retain control of the result.", icon: Sparkles },
  { label: "Blog Media", title: "Ideas with useful context", text: "Browse technical perspectives and media from Inzaghi's Blog Aggregator.", icon: Newspaper },
];

export default function Home() {
  return <AppShell>
    <section className="border-b border-border"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-6 sm:py-24 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:px-8 lg:py-28"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-primary">Practical intelligence, in one place</p><h1 className="mt-5 max-w-3xl text-4xl font-semibold tracking-tight text-foreground sm:text-5xl lg:text-6xl">A clearer way to work with digital tools and AI.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">InzaTech brings together useful tools, focused AI apps, information widgets, and specialized portals in one dependable ecosystem.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/explore" className="inline-flex h-11 items-center justify-center gap-2 rounded-md bg-primary px-5 text-sm font-semibold text-primary-foreground transition-opacity hover:opacity-90">Explore tools <ArrowRight size={17} aria-hidden="true" /></Link><Link href="/ai-apps" className="inline-flex h-11 items-center justify-center rounded-md border border-border bg-card px-5 text-sm font-semibold text-foreground transition-colors hover:bg-muted">Explore AI Apps</Link></div></div><div className="border border-border bg-card p-6 shadow-sm sm:p-8"><p className="font-mono text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">InzaTech ecosystem</p><dl className="mt-7 divide-y divide-border">{[["Tools", "Make routine technical work easier."], ["AI Apps", "Create and reason with focused AI interfaces."], ["Widgets & Portals", "Keep useful information and learning within reach."]].map(([term, description]) => <div key={term} className="py-4 first:pt-0"><dt className="font-semibold text-foreground">{term}</dt><dd className="mt-1 text-sm leading-6 text-muted-foreground">{description}</dd></div>)}</dl></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="max-w-2xl"><p className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-primary">The platform</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">One product, distinct places to get things done.</h2><p className="mt-4 leading-7 text-muted-foreground">Each area is designed around a job to be done, while sharing the same considered experience.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{areas.map(({ title, text, href, icon: Icon }) => <Link key={title} href={href} className="group border border-border bg-card p-6 transition-colors hover:border-primary/50 hover:bg-secondary"><Icon size={22} className="text-primary" aria-hidden="true" /><h3 className="mt-7 font-semibold text-foreground">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-primary">View area <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" aria-hidden="true" /></span></Link>)}</div></section>
    <section className="border-y border-border bg-muted"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-primary">Built for momentum</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Useful, not noisy.</h2><p className="mt-4 max-w-md leading-7 text-muted-foreground">A measured interface that keeps actions obvious, information readable, and every area connected.</p><Link href="/services" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline">See InzaTech services <ArrowRight size={16} aria-hidden="true" /></Link></div><div className="grid gap-4 sm:grid-cols-3">{highlights.map(({ label, title, text, icon: Icon }) => <article key={title} className="border border-border bg-card p-5"><Icon size={20} className="text-primary" aria-hidden="true" /><p className="mt-6 font-mono text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">{label}</p><h3 className="mt-2 font-semibold leading-6 text-foreground">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="border border-border bg-card px-6 py-10 sm:px-10"><div className="max-w-2xl"><p className="font-mono text-xs font-semibold uppercase tracking-[0.16em] text-primary">Start exploring</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Find the right utility for the work in front of you.</h2><p className="mt-4 leading-7 text-muted-foreground">Browse tools, discover dedicated AI apps, or explore the knowledge portals designed for your next task.</p><Link href="/explore" className="mt-7 inline-flex h-11 items-center justify-center gap-2 rounded-md bg-primary px-5 text-sm font-semibold text-primary-foreground transition-opacity hover:opacity-90">Browse Explore <ArrowRight size={17} aria-hidden="true" /></Link></div></div></section>
  </AppShell>;
}
